/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Util.DBConnection;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gauri
 */
public class ContractLedger extends javax.swing.JPanel {

    /**
     * Creates new form ContractLedger
     * 
     */
    Connection con=null;
    Statement st;
     public static DefaultTableModel   mod1;
    JTable service_table;
    private JScrollPane scrollpane;
    DefaultListModel info1 =new DefaultListModel();
     Dimension screenSize= Toolkit.getDefaultToolkit().getScreenSize();
     
        public ContractLedger() {
        initComponents();
         mod1 = (DefaultTableModel)jTable1.getModel();
       
         
         try{
            
          con = DBConnection.getConnection();
          Statement st =con.createStatement();
          //Object ob[] = new Object[4];
          
        ResultSet rs3=st.executeQuery("Select Name from customer_info");
          
            while(rs3.next()){
             name.addItem(rs3.getString("Name"));
            }
         
           
        }
        catch(Exception e)
        {
            
        } 
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        date = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        laborNo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lablorSal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lcost = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        name = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 153, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        jPanel6.setBackground(new java.awt.Color(0, 153, 153));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel4.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Contract Id");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(20, 10, 150, 50);

        cid.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidActionPerformed(evt);
            }
        });
        jPanel4.add(cid);
        cid.setBounds(180, 20, 50, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Date");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(500, 10, 80, 40);

        date.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel4.add(date);
        date.setBounds(570, 20, 200, 30);

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setText("Add Vehicle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);
        jButton1.setBounds(410, 250, 190, 40);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Labor Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("No. of present Labor");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 220, 40));

        laborNo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        laborNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laborNoActionPerformed(evt);
            }
        });
        jPanel1.add(laborNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 110, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Salary of labor per day");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 240, 40));

        lablorSal.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lablorSal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lablorSalFocusLost(evt);
            }
        });
        lablorSal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lablorSalActionPerformed(evt);
            }
        });
        lablorSal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lablorSalKeyReleased(evt);
            }
        });
        jPanel1.add(lablorSal, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 110, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Total Labor Cost");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 200, 40));

        lcost.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(lcost, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 110, 30));

        jPanel4.add(jPanel1);
        jPanel1.setBounds(40, 70, 440, 170);

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vehicle Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Vehicle No", "Material", "Quantity", "Fuel left ", "No. of trips", "Milage", "Fuel filled", "Distance in single trip"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 1190, 240));

        jPanel4.add(jPanel2);
        jPanel2.setBounds(10, 300, 1220, 290);

        name.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel4.add(name);
        name.setBounds(250, 20, 220, 30);

        jButton2.setBackground(new java.awt.Color(255, 102, 102));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton2.setText("SAVE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2);
        jButton2.setBounds(1130, 590, 100, 40);

        jPanel6.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 1250, 640));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Contract Ledger");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 330, 90));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\gauri\\OneDrive\\Pictures\\Camera Roll\\CAL1.png")); // NOI18N
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 90));

        jPanel6.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 1250, 80));

        add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 1360, 810));
    }// </editor-fold>//GEN-END:initComponents

    private void laborNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laborNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_laborNoActionPerformed

    private void lablorSalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lablorSalKeyReleased
        // TODO add your handling code here:
    
    }//GEN-LAST:event_lablorSalKeyReleased

    private void lablorSalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lablorSalFocusLost
        // TODO add your handling code here:
        Float labor= Float.parseFloat(laborNo.getText());
        Float laborsalary=  Float.parseFloat(lablorSal.getText());
        Float totalCost = labor * laborsalary;
        lcost.setText(totalCost.toString());
    }//GEN-LAST:event_lablorSalFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
       // Vehicle_info cl=new  Vehicle_info();
        //cl.setBounds(0,0,screenSize.width,screenSize.height);
      //  this.add(cl);
      
                    JFrame fr = new JFrame();
                    fr.setSize(1500,1000);
                    fr.setTitle("Advance Details");
                    fr.setVisible(true);
                    int slipno=0;
                    VehicleDetails ck = new VehicleDetails();
                    ck.setBounds(50, 50, 900, 900);
                    fr.add(ck);
                    Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
                    // this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
                    fr.setLocation(dim.width /10, dim.height / 10);
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         float materialRate=(float) 0.0;
         for(int i=0; i< mod1.getRowCount();i++)
            {
               
                if(!mod1.getValueAt(i, 4).toString().equalsIgnoreCase("")){
                float materialRate1=Float.parseFloat(mod1.getValueAt(i, 4).toString());
                materialRate = materialRate + materialRate1;
                }
            }
        
        try {
			Connection con = DBConnection.getConnection();

			PreparedStatement ps = con.prepareStatement("insert into  con_leg_basic values(?,?,?,?,?,?)");
                        ps.setInt(1,Integer.parseInt(cid.getText()));
                        java.sql.Date sqlDate=null;
                        java.util.Date dateFromDateChooser = date.getDate();
                        if(dateFromDateChooser!=null){
                        sqlDate = new java.sql.Date(dateFromDateChooser.getTime());

                        }      
                        ps.setDate(2,sqlDate);
                        ps.setInt(3,Integer.parseInt(laborNo.getText()));
                        ps.setInt(4,Integer.parseInt(lablorSal.getText()));
                        ps.setDouble(5,Float.parseFloat(lcost.getText()));
                        ps.setDouble(6,materialRate);
                  
                        ps.executeUpdate();
                     JOptionPane.showMessageDialog(null, "Contract Added Successfully");
                   
                     
             for(int i=0; i< mod1.getRowCount();i++)
            {
                      String mname= mod1.getValueAt(i, 2).toString();
                      System.out.println(getId(mname));
                      String mid1 =""; 
                if(!mod1.getValueAt(i, 1).toString().equalsIgnoreCase("")){
                        PreparedStatement ps1 = con.prepareStatement("insert into  con_leg_vehicle values(?,?,?,?,?,?,?,?,?,?)");
                        ps1.setInt(1,Integer.parseInt(cid.getText()));
                        ps1.setString(2,mod1.getValueAt(i, 1).toString());
                        ps1.setString(3,getId(mname));
                        ps1.setString(4,mod1.getValueAt(i, 3).toString());
                        ps1.setString(5,mod1.getValueAt(i, 4).toString());
                        ps1.setString(6,mod1.getValueAt(i, 5).toString());
                        ps1.setString(7,mod1.getValueAt(i, 6).toString());
                        ps1.setString(8,mod1.getValueAt(i, 7).toString());
                        ps1.setString(9,mod1.getValueAt(i, 8).toString());
                        ps1.setDate(10,sqlDate);
                  
                        ps1.executeUpdate();
                      // JOptionPane.showMessageDialog(null, "Contract Added Successfully");
            }

            }	con.close();
		} catch (Exception ex) {
			ex.printStackTrace();
		}

    }//GEN-LAST:event_jButton2ActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
         String Name=(name.getSelectedItem().toString());
        try{

            con = DBConnection.getConnection();
            Statement st =con.createStatement();

            ResultSet rs3=st.executeQuery("SELECT id FROM magsys.contract_info where Name='"+Name+"'");
            while(rs3.next())
            {
               cid.setText(""+rs3.getInt("id"));
            }
        }
        catch(Exception e)
        {

        }
    }//GEN-LAST:event_nameActionPerformed

    private void cidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cidActionPerformed

    private void lablorSalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lablorSalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lablorSalActionPerformed

    public String getId(String name){
     String id ="";
        try{

            con = DBConnection.getConnection();
            Statement st =con.createStatement();

            ResultSet rs3=st.executeQuery("Select M_Id from material_info where M_Name='"+name+"'");
            while(rs3.next())
            {
               id = ""+rs3.getInt("M_Id");
               
            }
        }
        catch(Exception e)
        {

        } 
        
       return id; 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cid;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1;
    private javax.swing.JTextField lablorSal;
    private javax.swing.JTextField laborNo;
    private javax.swing.JTextField lcost;
    private javax.swing.JComboBox<String> name;
    // End of variables declaration//GEN-END:variables
}
