/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Util.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author gauri
 */
public class payment extends javax.swing.JPanel {
   Connection con=null;
    public payment() {
        initComponents();
        
         try{
            
          con = DBConnection.getConnection();
          Statement st =con.createStatement();
          //Object ob[] = new Object[4];
          
        ResultSet rs3=st.executeQuery("Select Name from customer_info");
          
            while(rs3.next()){
             name.addItem(rs3.getString("Name"));
            }
         
           
        }
        catch(Exception e)
        {
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        date = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        value = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        bill2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        bill = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel7.setText("Payment");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 200, 70));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\gauri\\OneDrive\\Pictures\\Camera Roll\\pp11.jpg")); // NOI18N
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 90));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 930, 90));

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Contract Id");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 220, 50));

        id.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        id.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                idFocusLost(evt);
            }
        });
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idKeyTyped(evt);
            }
        });
        jPanel3.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 90, 40));

        date.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel3.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, 190, 40));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Date");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 90, 40));

        name.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel3.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 230, 40));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Customer Name");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 280, 40));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Contract Total Bill");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 310, 40));

        value.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        value.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                valueFocusGained(evt);
            }
        });
        value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valueActionPerformed(evt);
            }
        });
        jPanel3.add(value, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 230, 40));

        jButton2.setBackground(new java.awt.Color(255, 204, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton2.setText("Check");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, 90, 40));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Amount Received");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 300, 40));

        bill2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel3.add(bill2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 230, 40));

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("Pay");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 100, 40));

        bill.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billActionPerformed(evt);
            }
        });
        jPanel3.add(bill, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 390, 230, 40));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Balance  ");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 390, 180, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 930, 450));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 1110, 670));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int conId = 0;
        int cont_id = Integer.parseInt(id.getText());
        double bal =0.0;
        bal= Float.parseFloat(value.getText()) - Float.parseFloat(bill2.getText());
        bill.setText(""+bal);
          try {
			Connection con = DBConnection.getConnection();
                          Statement st =con.createStatement();
                     double balBill=  Float.parseFloat(bill.getText());
                         ResultSet rs4 = st.executeQuery("SELECT Count(contract_Id) as cid FROM magsys.payment where contract_Id="+cont_id);
             while(rs4.next())
            {
              conId = rs4.getInt("cid");
               
            }
          
                      if(conId==0)
             {  
			PreparedStatement ps = con.prepareStatement("insert into  payment values(?,?,?,?,?,?)");
                        ps.setInt(1,Integer.parseInt(id.getText()));
                        ps.setString(2,name.getSelectedItem().toString());
                        java.sql.Date sqlDate=null;
                        java.util.Date dateFromDateChooser = date.getDate();
                        if(dateFromDateChooser!=null){
                        sqlDate = new java.sql.Date(dateFromDateChooser.getTime());

                        }      
                        ps.setDate(3,sqlDate);
                        ps.setDouble(4,Float.parseFloat(value.getText()));
                        ps.setDouble(5,Float.parseFloat(bill2.getText()));
                        ps.setDouble(6,Float.parseFloat(bill.getText()));
                       
                  
                        ps.executeUpdate();
                     JOptionPane.showMessageDialog(null, "Bill Paid");
             }
                      else{
                        PreparedStatement psmt = con.prepareStatement("update payment set totalAmt=?, date=?, bal=?,pay=? where contract_Id="+cont_id);
                        psmt.setDouble(1,Float.parseFloat(value.getText()));
                        java.sql.Date sqlDate=null;
                        java.util.Date dateFromDateChooser = date.getDate();
                        if(dateFromDateChooser!=null){
                        sqlDate = new java.sql.Date(dateFromDateChooser.getTime());

                        }      
                        psmt.setDate(2,sqlDate);
                        psmt.setDouble(3,Float.parseFloat(bill.getText()));
                        psmt.setDouble(4,Float.parseFloat(bill2.getText())); 
                        psmt.executeUpdate();
                         JOptionPane.showMessageDialog(null, "Bill Paid");
                      }
              	
		} catch (Exception ex) {
			ex.printStackTrace();
		}
          
               // clear data
         id.setText("");
         name.setSelectedItem("");
         //date.setDateFormatString("");
         value.setText("");
         bill2.setText("");
         bill.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void idFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idFocusLost
        // TODO add your handling code here:
         
    }//GEN-LAST:event_idFocusLost

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void valueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valueActionPerformed

    private void billActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_billActionPerformed

    private void idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_idKeyTyped

    private void valueFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_valueFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_valueFocusGained

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
             try{ 
        int conId = 0;
       int cont_id1 = Integer.parseInt(id.getText());
         float billRate =(float) 0.0;
      

            con = DBConnection.getConnection();
            Statement st =con.createStatement();

            ResultSet rs4 = st.executeQuery("SELECT Count(contract_Id) as cid FROM magsys.payment where contract_Id="+cont_id1);
             while(rs4.next())
            {
              conId = rs4.getInt("cid");
               
            }
          
             if(conId==0)
             {
             
            ResultSet rs3=st.executeQuery("Select c.contract_id,m.rate,c.material,c.quantity , m.rate *c.quantity as totalmrate  from magsys.contract_material_info m left join  \n" +
"magsys.con_leg_vehicle c on m.material_id = c.material where c.contract_id ="+cont_id1);
            while(rs3.next())
            {
               billRate = billRate + Float.parseFloat(rs3.getString("totalmrate"));
               
            }
          value.setText(""+billRate);
            
        }
             else{
                    ResultSet rs5=st.executeQuery("SELECT  bal FROM magsys.payment where contract_Id="+cont_id1);
            while(rs5.next())
            {
               billRate = Float.parseFloat(rs5.getString("bal"));
               
            }
          value.setText(""+billRate); 
             }
             
         } catch(Exception e)
        {

        } 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
        
          String Name=(name.getSelectedItem().toString());
        try{

            con = DBConnection.getConnection();
            Statement st =con.createStatement();

            ResultSet rs3=st.executeQuery("SELECT id FROM magsys.contract_info where Name='"+Name+"'");
            while(rs3.next())
            {
               id.setText(""+rs3.getInt("id"));
            }
        }
        catch(Exception e)
        {

        }
    }//GEN-LAST:event_nameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bill;
    private javax.swing.JTextField bill2;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JComboBox<String> name;
    private javax.swing.JTextField value;
    // End of variables declaration//GEN-END:variables
}
