package View;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import Util.DBConnection;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gauri
 */
public class VehicleDetails extends javax.swing.JPanel {
  
    // HomePage hp;
     //Dimension screenSize= Toolkit.getDefaultToolkit().getScreenSize();
    /**
     * Creates new form Vehicle_info
     */
    DefaultTableModel mod;
    Connection con=null;
    
    public VehicleDetails() {
        
        initComponents();
        
        
         mod = (DefaultTableModel)jTable1.getModel();
         
         try{
            
          con = DBConnection.getConnection();
          Statement st =con.createStatement();
          //Object ob[] = new Object[4];
          
          ResultSet rs3=st.executeQuery("Select Number from vehicle_info");
          while(rs3.next())
          {
              vehicle.addItem(rs3.getString("Number"));
          }
         
          ResultSet rs4=st.executeQuery("Select M_Name from material_info");
          while(rs4.next())
          {
              material.addItem(rs4.getString("M_Name"));
              
          }  
        }
        catch(Exception e)
        {
            
        }
         System.out.println(id); 
        
        

    }
 
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        vehicle = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        material = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        quantity = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        trips = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        fuelF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        fuelL = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        dTrip = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        milage = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel8.setText("jLabel8");

        setBackground(new java.awt.Color(0, 0, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel2.setForeground(new java.awt.Color(0, 102, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Vehical Information");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 390, 60));

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\gauri\\OneDrive\\Pictures\\Camera Roll\\vvv100.jpg")); // NOI18N
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 90));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 90));

        id.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 260, 40));

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 400, 120, 50));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Id");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 40, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("VehicleNO");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 120, 40));

        vehicle.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        vehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleActionPerformed(evt);
            }
        });
        jPanel1.add(vehicle, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 260, 40));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Material");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 100, 40));

        material.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        material.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                materialMouseClicked(evt);
            }
        });
        jPanel1.add(material, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 260, 40));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Quantity");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 100, 40));

        quantity.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 260, 40));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Trips");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 70, 40));

        trips.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        trips.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tripsActionPerformed(evt);
            }
        });
        jPanel1.add(trips, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, 230, 40));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Fuel Filled");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, -1, -1));

        fuelF.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        fuelF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fuelFActionPerformed(evt);
            }
        });
        jPanel1.add(fuelF, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, 230, 40));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Fuel Left");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 100, 40));

        fuelL.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(fuelL, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 240, 230, 40));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Distance in single trip");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, -1, 40));

        dTrip.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        dTrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dTripActionPerformed(evt);
            }
        });
        jPanel1.add(dTrip, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 300, 110, 40));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Milage");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 90, 40));

        milage.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        milage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                milageActionPerformed(evt);
            }
        });
        jPanel1.add(milage, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 260, 40));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 840, 550));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 1040, 690));
    }// </editor-fold>//GEN-END:initComponents

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
   ContractLedger.mod1.insertRow(ContractLedger.mod1.getRowCount(),new  String []{""+id.getText(),""+vehicle.getSelectedItem(),""+material.getSelectedItem(),""+quantity.getText(),""+fuelL.getText(),
      ""+trips.getText(), ""+milage.getText(),""+fuelF.getText(),""+dTrip.getText()});
   
          //clear data
         id.setText("");
         quantity.setText("");
         fuelL.setText("");
         vehicle.setSelectedItem("");
         trips.setText("");
         milage.setText("");
         material.setSelectedItem("");
         fuelF.setText("");
         dTrip.setText("");
         
         jButton1.setEnabled(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tripsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tripsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tripsActionPerformed

    private void fuelFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fuelFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fuelFActionPerformed

    private void dTripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dTripActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dTripActionPerformed

    private void vehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleActionPerformed
        // TODO add your handling code here:
          
    }//GEN-LAST:event_vehicleActionPerformed

    private void materialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_materialMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_materialMouseClicked

    private void milageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_milageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_milageActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dTrip;
    private javax.swing.JTextField fuelF;
    private javax.swing.JTextField fuelL;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> material;
    private javax.swing.JTextField milage;
    private javax.swing.JTextField quantity;
    private javax.swing.JTextField trips;
    private javax.swing.JComboBox<String> vehicle;
    // End of variables declaration//GEN-END:variables

}