/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


import Util.DBConnection;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;



/**
 *
 * @author gauri
 */
public class View_contract extends javax.swing.JPanel {
     /**
     * Creates new form Create_user
     */
    
     Connection con=null;
    Statement st;
     DefaultTableModel mod1,mod2,mod3;
    JTable service_table;
    private JScrollPane scrollpane;
    DefaultListModel info1 =new DefaultListModel();
    
    
    public View_contract() {
        initComponents();
         JTableHeader jh =vtable.getTableHeader();
         jh.setFont(new Font("plain",Font.BOLD,14));
         jh.setBackground(Color.PINK);
         
         
         mod1 = (DefaultTableModel)vtable.getModel();
         
         try{
            
          con = DBConnection.getConnection();
          st =con.createStatement();
          
           //Customer Name 
           ResultSet rs1=st.executeQuery("Select Name from customer_info");
           ArrayList<String>custname  = new ArrayList<String>();
            while(rs1.next()){
             custname.add(rs1.getString("Name"));
            }  
            cname.addItem("All");
            for(int x=0;x<custname.size();x++)
            {
               cname.addItem(custname.get(x));
           } 
            
             //project
              ResultSet rs2=st.executeQuery("Select P_Name from project_info");
              ArrayList<String>projectname  = new ArrayList<String>();
                while(rs2.next()){
                   projectname.add(rs2.getString("P_Name"));
                 }  
             projectcombo.addItem("All");
            for(int x=0;x<projectname.size();x++)
            {
               projectcombo.addItem(projectname.get(x));
           } 
            
            
             //site
              ResultSet rs3=st.executeQuery("Select site_Name from site");
           ArrayList<String>sitename  = new ArrayList<String>();
            while(rs3.next()){
             sitename.add(rs3.getString("site_Name"));
            }  
             sitecom.addItem("All");
            for(int x=0;x<sitename.size();x++)
            {
               sitecom.addItem(sitename.get(x));
           } 
            
            
            //material
              ResultSet rs4 = st.executeQuery("Select M_Name from material_info");
           ArrayList<String>materialname  = new ArrayList<String>();
            while(rs4.next()){
             materialname.add(rs4.getString("M_Name"));
            }  
            
            for(int x=0;x<materialname.size();x++)
            {
              // mterial.addItem(materialname.get(x));
           } 
            
             //vehicle
              ResultSet rs5 = st.executeQuery("Select Number from vehicle_info");
           ArrayList<String>vehiclename  = new ArrayList<String>();
            while(rs5.next()){
             vehiclename.add(rs5.getString("Number"));
            }  
            
            for(int x=0;x<vehiclename.size();x++)
            {
              // vehicleno.addItem(vehiclename.get(x));
           } 
    }  
          catch(Exception e)
        {
            
        }
         
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendarTheme1 = new com.toedter.plaf.JCalendarTheme();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cname = new javax.swing.JComboBox<>();
        projectcombo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        sitecom = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        vtable = new javax.swing.JTable();

        setBackground(new java.awt.Color(51, 51, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText(" View Contract");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(160, 10, 270, 70);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\gauri\\OneDrive\\Pictures\\Camera Roll\\vi123.jpg")); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 150, 90);

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 1040, 90));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3), "Search Criteria", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 18))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 70, 50));

        cname.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnameActionPerformed(evt);
            }
        });
        jPanel2.add(cname, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 190, 40));

        projectcombo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel2.add(projectcombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 190, 40));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Project");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 100, 40));

        sitecom.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel2.add(sitecom, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 40, 170, 40));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Site");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 43, 60, 30));

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Search.png"))); // NOI18N
        jButton1.setText("  VIEW");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 40, 140, 40));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 1040, 100));

        vtable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        vtable.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        vtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Con. Id", "Name", "Site", "Project"
            }
        ));
        vtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vtableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(vtable);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 1040, 530));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 1210, 830));
    }// </editor-fold>//GEN-END:initComponents

    private void cnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
             if(mod1.getRowCount()>0)
            {
                for(int k=mod1.getRowCount()-1;k>-1;k--)
                {
                    mod1.removeRow(k);
                }
            }
        
        
          
        try{
         String name=cname.getSelectedItem().toString();
        String prname=projectcombo.getSelectedItem().toString();
        String srname= sitecom.getSelectedItem().toString();
          StringBuilder sb =new StringBuilder();
        
        if(!name.equalsIgnoreCase("All")){
            sb.append(" where Name="+"'"+name+"'");      
        }
        
         if(!prname.equalsIgnoreCase("All") &&   !name.equalsIgnoreCase("All") ){
            sb.append(" and Project="+"'"+prname+"'");      
        }
         
         if(!prname.equalsIgnoreCase("All") &&  name.equalsIgnoreCase("All") ){
            sb.append(" where Project="+"'"+prname+"'");      
        }
          if(!prname.equalsIgnoreCase("All") &&  !name.equalsIgnoreCase("All") ){
            sb.append(" and Project="+"'"+prname+"'");      
           }
         
         if(!prname.equalsIgnoreCase("All") &&  name.equalsIgnoreCase("All") && !srname.equalsIgnoreCase("All") ){
            sb.append(" where Site="+"'"+srname+"'");      
           }
        if(prname.equalsIgnoreCase("All") &&  name.equalsIgnoreCase("All") && !srname.equalsIgnoreCase("All")){
            sb.append(" where Site="+"'"+srname+"'");      
           }
        
         con =DBConnection.getConnection();
        Statement stmt=con.createStatement();
        
        ResultSet rs1=stmt.executeQuery("Select * from contract_info "+sb+" ");
        
        while(rs1.next()){
           int id=rs1.getInt("id");
           String pname=rs1.getString("Name");
           String site=rs1.getString("Site");
           String project=rs1.getString("Project");
           
            mod1.insertRow(mod1.getRowCount(),new  String []{""+id,""+pname,""+site,""+project});
            
           
        }
        
        }
        catch(Exception e){
            
        }
        

         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void vtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vtableMouseClicked
        // TODO add your handling code here:
        int i=vtable.getSelectedRow();
        String cid =mod1.getValueAt(i,0).toString();
           JFrame fr = new JFrame();
                    fr.setSize(1700, 1500);
                    fr.setTitle("Advance Details");
                    fr.setVisible(true);
                    int slipno=0;
                    View_leger_details ck = new View_leger_details(cid);
                    ck.setBounds(50, 50, 900, 900);
                    fr.add(ck);
                    Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
                    // this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
                    fr.setLocation(dim.width /50, dim.height / 50);
    }//GEN-LAST:event_vtableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cname;
    private javax.swing.JButton jButton1;
    private com.toedter.plaf.JCalendarTheme jCalendarTheme1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> projectcombo;
    private javax.swing.JComboBox<String> sitecom;
    private javax.swing.JTable vtable;
    // End of variables declaration//GEN-END:variables
}
